
import '../style/Gallerry.scss'

function ImageGallery() {
  return (
    <div className='image_gallery_Container'>
<div className='intro_Section'>
    <h1>Popular NFT’s generated by Artists</h1>
    <p> 3dotlink's AI integration is a game-changer in the NFT art world. It offers a powerful canvas for artists to redefine art creation and innovation while preserving cultural art in an entirely new format. With this platform, the convergence of human ingenuity and AI technology is set to redefine the boundaries of artistic expression and creative possibilities, ushering in a digital art renaissance.</p>
</div>
        
{/* Gallery SEction */}

<div className='gallery-section'>
<div className='gallery-leftSide'>
    <img src="imgs/gallery1.png" alt="" />
    <img src="imgs/gallery2.png" alt="" />
</div>

<div className='gallery-rightside'>

<div className='gallery-rightside_FirstSection'>
    
<div><img src="imgs/gallery3.png" alt="" /></div>

<div>
<img src="imgs/gallery4.png" alt="" />
<img src="imgs/gallery5.png" alt="" />

</div>
</div>


<div className='gallery-rightside_secondSection'>
<img src="imgs/gallery6.png" alt="" />
<img src="imgs/gallery7.png" alt="" />
</div>

</div>

</div>

        </div>
  )
}

export default ImageGallery